### ISSUE TITLE
Lack of class to style the search-bar

### ISSUE THREAD

**Issue by perillosantana** [vtex-apps/search#103]
**Is your feature request related to a problem? Please describe.**
There is no class to manipulate the element that is absolute.

![alt text](https://i.ibb.co/sF1NtfV/Tela-inteira-21-10-2020-14-12.png)

**Describe the solution you'd like**
With a class in the element, I can manipulate (force) the position and the ideal size to match the layout.

**Comment by thalytafabrine** [comment]
Hi @perillosantana, I think you can change position or size inside the div that has class `vtex-search-2-x-biggy-autocomplete-wrapper`.
Have you tried to do this with [`blockClass`](https://vtex.io/docs/recipes/style/using-css-handles-for-store-customization/)?

**Comment by perillosantana** [comment]
Hi @thalytafabrine, I already tried to do this, but I need the class in the element that is being manipulated with the absolute, so I can make it dynamic (size and position).

**Comment by thalytafabrine** [comment]
@perillosantana can you provide a workspace to test it?

**Comment by perillosantana** [comment]
Hi @thalytafabrine, you can use this workspace in that environment:
[vtextest--drinkrunnr.myvtex.com](https://vtextest--drinkrunnr.myvtex.com/)

**Comment by thalytafabrine** [comment]
@perillosantana  it seems to me that the size in the autocomplete has already been adjusted 🤔 
what problem are you still having?

![image](https://user-images.githubusercontent.com/20840671/98689974-372ac000-234b-11eb-8fa7-efe22b0a017d.png)
![image](https://user-images.githubusercontent.com/20840671/98690370-9f79a180-234b-11eb-9f87-f3755217e91b.png)

**Comment by perillosantana** [comment]
@thalytafabrine We put a fixed size for a presentation that the client would make, but if I remove the size, it will always be `100vw`, the class in the item with absolute would help me deal with that size and positioning.

![](https://i.ibb.co/HFXwRCz/Tela-inteira-10-11-2020-17-212.png)

**Comment by thalytafabrine** [comment]
@perillosantana the size will always be `100vw` because this is the value you are passing in your store-theme:

![image](https://user-images.githubusercontent.com/20840671/98813468-f4c4ba00-2402-11eb-9b13-af07c42215f0.png)

but if you can control the size in this div using `biggy-autocomplete-wrapper` you can do what you want, right? this div with the `absolute` class is not part of the `vtex.search` app, so I can't add a new class to it.

I also did a test to change the size according with the screen [in your wks](https://vtextest--drinkrunnr.myvtex.com/) and it worked:

![image](https://user-images.githubusercontent.com/20840671/98817836-80414980-2409-11eb-980e-164ba0e541c4.png)
![image](https://user-images.githubusercontent.com/20840671/98817881-918a5600-2409-11eb-9434-b1df7b78c992.png)


please, let me know if you need anything else :)

**Comment by thalytafabrine** [comment]
I will close this issue as no new comments have appeared. if you need help again, just reopen and @ me here. thanks! 👋 🙂
